---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse
    tag:        latest

inputs:
- name: boshrelease
- name: boshrelease-ci
- name: docker-image-pg93
  path: images/cfcommunity_postgresql_9_3_image
- name: docker-image-pg94
  path: images/cfcommunity_postgresql_9_4_image
- name: docker-image-pg95
  path: images/cfcommunity_postgresql_9_5_image
- name: docker-image-pg96
  path: images/cfcommunity_postgresql_9_6_image

outputs:
- name: boshrelease-images-updated

params:
  aws_access_key_id:
  aws_secret_access_key:

run:
  path: boshrelease-ci/ci/tasks/bump-image-layers.sh
